<?php

namespace Tests\Unit\Models\CrewModels;

class FindCrewForFlightTest extends \Tests\Unit\Models\ModelTestBaseClass
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }
}